-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT 
from ONLINE_SALE
where MONTH(SALES_DATE)=03 AND YEAR(SALES_DATE)=2022
union
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT 
from OFFLINE_SALE
where MONTH(SALES_DATE)=03 AND YEAR(SALES_DATE)=2022
order by SALES_DATE ASC, PRODUCT_ID ASC, USER_ID asc