select count(*) COUNT
from ECOLI_DATA
where SUBSTRING(LPAD(RIGHT(BIN(GENOTYPE),4),4,0),-2,1) = '0'
and (SUBSTRING(LPAD(RIGHT(BIN(GENOTYPE),4),4,0),-1,1) = '1'
    or SUBSTRING(LPAD(RIGHT(BIN(GENOTYPE),4),4,0),-3,1) = '1')