-- 코드를 입력하세요
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,(sum(O.AMOUNT)*P.PRICE) TOTAL_SALES
from FOOD_PRODUCT P, FOOD_ORDER O
where P.PRODUCT_ID=O.PRODUCT_ID
and O.PRODUCE_DATE like '2022-05%'
group by PRODUCT_ID
order by TOTAL_SALES desc , PRODUCT_ID asc
