-- 코드를 입력하세요
SELECT I.REST_ID as REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,ROUND(AVG(R.REVIEW_SCORE),2) as SCORE
from REST_INFO I, REST_REVIEW R
where I.REST_ID=R.REST_ID AND I.ADDRESS like '서울%'
group by R.REST_ID
order by score desc, I.FAVORITES desc